import { z } from 'zod'

const periodSchema = z.enum(['today', '7d', '30d'])
const captureStateSchema = z.enum(['captured', 'metadata_only', 'expired'])
const redactionStateSchema = z.enum(['passed', 'review_required', 'not_applicable'])
const groupingSchema = z.enum(['conversation', 'independent_call'])
const optionSchema = z.object({ id: z.string(), label: z.string() })

export const conversationAuditFiltersSchema = z.object({ period: periodSchema, search: z.string().max(80), person: z.string(), key: z.string(), purpose: z.string(), model: z.string(), policy: z.string(), state: z.union([z.literal('all'), captureStateSchema]), redaction: z.union([z.literal('all'), redactionStateSchema]), grouping: z.union([z.literal('all'), groupingSchema]), page: z.number().int().positive(), pageSize: z.number().int().min(5).max(50) })
export const conversationRecordSchema = z.object({
  id: z.string(), requestId: z.string().regex(/^req-[a-z0-9-]+$/), capturedAt: z.string().datetime(), person: z.object({ id: z.string(), name: z.string(), department: z.string() }), key: z.object({ id: z.string(), masked: z.string() }), purpose: optionSchema, model: z.object({ id: z.string(), label: z.string() }), policy: z.object({ id: z.string(), label: z.string(), scope: z.string(), expiresAt: z.string().datetime() }), state: captureStateSchema, redaction: z.object({ status: redactionStateSchema, findings: z.number().int().nonnegative(), rawContentAvailable: z.literal(false) }), grouping: z.object({ type: groupingSchema, reliable: z.boolean(), label: z.string() }), metrics: z.object({ turns: z.number().int().nonnegative(), toolCalls: z.number().int().nonnegative(), totalTokens: z.number().int().nonnegative() }), contentAccess: z.object({ available: z.boolean(), requiresReason: z.literal(true), requiredRole: z.literal('super_admin') }),
})
export const conversationAuditResponseSchema = z.object({
  meta: z.object({ source: z.literal('demo'), generatedAt: z.string().datetime(), period: periodSchema, notice: z.string() }), accessControl: z.object({ currentRole: z.literal('super_admin'), serverRbacVerified: z.literal(false), contentRequiresReason: z.literal(true), notice: z.string() }), summary: z.object({ total: z.number().int().nonnegative(), captured: z.number().int().nonnegative(), metadataOnly: z.number().int().nonnegative(), expiringSoon: z.number().int().nonnegative(), independentCalls: z.number().int().nonnegative(), reviewRequired: z.number().int().nonnegative() }), scope: z.object({ defaultCaptureEnabled: z.literal(false), activePolicies: z.number().int().nonnegative(), nearestExpiryAt: z.string().datetime(), storageEncryptedVerified: z.literal(false), accessAuditPersisted: z.literal(false), notice: z.string() }), options: z.object({ people: z.array(optionSchema), keys: z.array(optionSchema), purposes: z.array(optionSchema), models: z.array(optionSchema), policies: z.array(optionSchema) }), items: z.array(conversationRecordSchema), pagination: z.object({ page: z.number().int().positive(), pageSize: z.number().int().positive(), total: z.number().int().nonnegative(), totalPages: z.number().int().nonnegative() }),
})
const messageSchema = z.object({ id: z.string(), role: z.enum(['user', 'assistant', 'tool']), label: z.string(), occurredAt: z.string().datetime(), text: z.string(), redacted: z.boolean(), redactionLabels: z.array(z.string()), tool: z.object({ name: z.string(), summary: z.string(), argumentsAvailable: z.literal(false), outputAvailable: z.literal(false) }).nullable() })
export const conversationAccessResponseSchema = z.object({
  meta: z.object({ source: z.literal('demo'), generatedAt: z.string().datetime(), notice: z.string() }), record: conversationRecordSchema, access: z.object({ accessRecordId: z.string(), reasonAccepted: z.literal(true), persisted: z.literal(false), authorizedByServerRbac: z.literal(false), copyAllowed: z.literal(false), exportAllowed: z.literal(false), deleteAllowed: z.literal(false) }), content: z.object({ synthetic: z.literal(true), decrypted: z.literal(false), redactionPassed: z.boolean(), conversationTitle: z.string(), messages: z.array(messageSchema) }), retention: z.object({ expiresAt: z.string().datetime(), cleanupState: z.enum(['scheduled', 'expired', 'not_applicable']), deletionProofAvailable: z.literal(false), notice: z.string() }), linkedUsage: z.object({ requestId: z.string(), metadataEndpoint: z.string(), requestIdVerified: z.literal(false) }),
})

export type ConversationAuditFilters = z.infer<typeof conversationAuditFiltersSchema>
export type ConversationAuditRecord = z.infer<typeof conversationRecordSchema>
export type ConversationAuditResponse = z.infer<typeof conversationAuditResponseSchema>
export type ConversationAccessResponse = z.infer<typeof conversationAccessResponseSchema>

export class ConversationAuditApiError extends Error { constructor(message: string, readonly requestId?: string) { super(message) } }
async function parseResponse<T>(response: Response, schema: z.ZodType<T>, fallback: string) { const requestId = response.headers.get('x-request-id') ?? undefined; if (!response.ok) throw new ConversationAuditApiError(response.status === 404 ? '该记录没有可访问的对话内容' : fallback, requestId); const parsed = schema.safeParse(await response.json()); if (!parsed.success) throw new ConversationAuditApiError('对话审计数据格式不符合接口约定', requestId); return parsed.data }
export async function fetchConversationAudits(filters: ConversationAuditFilters, signal?: AbortSignal) { const value = conversationAuditFiltersSchema.parse(filters); const params = new URLSearchParams(Object.entries(value).map(([key, item]) => [key, String(item)])); return parseResponse(await fetch(`/api/conversation-audits?${params}`, { headers: { accept: 'application/json' }, signal }), conversationAuditResponseSchema, '对话审计暂时无法加载') }
export async function requestConversationAccess(id: string, reason: string, signal?: AbortSignal) { return parseResponse(await fetch(`/api/conversation-audits/${encodeURIComponent(id)}/access`, { method: 'POST', headers: { accept: 'application/json', 'content-type': 'application/json' }, body: JSON.stringify({ reason, acknowledgeSensitiveScope: true }), signal }), conversationAccessResponseSchema, '无法打开脱敏轮次') }
