import { z } from 'zod'

const metaSchema = z.object({ source: z.literal('demo'), generatedAt: z.string().datetime(), notice: z.string() })
const scopeSchema = z.object({ mode: z.literal('self_demo'), currentUserVerified: z.literal(false), serverRbacVerified: z.literal(false), otherPeopleAvailable: z.literal(false), notice: z.string() })
export const employeeProfileResponseSchema = z.object({ meta: metaSchema, scope: scopeSchema, person: z.object({ id: z.literal('person-lin'), name: z.string(), initials: z.string(), employeeCode: z.string(), department: z.string(), role: z.literal('employee'), status: z.literal('active'), manager: z.string(), joinedAt: z.string().date() }), support: z.object({ contact: z.string(), serviceHours: z.string(), temporaryQuotaRequestAvailable: z.literal(false), notice: z.string() }), commonErrors: z.array(z.object({ code: z.enum(['AUTH_INVALID', 'MODEL_NOT_ALLOWED', 'SOFT_TARGET_REACHED', 'UPSTREAM_UNAVAILABLE']), title: z.string(), explanation: z.string(), action: z.string(), internalDetailAvailable: z.literal(false) })) })
const employeeKeySchema = z.object({ id: z.string(), masked: z.string(), purpose: z.string(), alias: z.string(), allowedModels: z.array(z.string()), status: z.enum(['active', 'expiring']), createdAt: z.string().datetime(), expiresAt: z.string().datetime(), lastUsedAt: z.string().datetime().nullable(), secretAvailable: z.literal(false), rotateAvailable: z.literal(false) })
export const employeeKeysResponseSchema = z.object({ meta: metaSchema, scope: scopeSchema, items: z.array(employeeKeySchema), connection: z.object({ baseUrl: z.string().url(), credentialDelivery: z.string(), upstreamDetailsAvailable: z.literal(false), guides: z.array(z.object({ id: z.enum(['codex', 'workbuddy']), name: z.string(), description: z.string(), steps: z.array(z.string()) })) }) })
export const employeeUsageResponseSchema = z.object({ meta: metaSchema.extend({ period: z.enum(['7d', '30d']) }), scope: scopeSchema, summary: z.object({ pointsUsed: z.number().int().nonnegative(), pointsTarget: z.number().int().positive(), pointsRemaining: z.number().int().nonnegative(), usagePercent: z.number().min(0), requests: z.number().int().nonnegative(), tokens: z.number().int().nonnegative(), successRate: z.number().min(0).max(100), softTarget: z.literal(true), requestBlockingEnabled: z.literal(false) }), trend: z.array(z.object({ date: z.string().date(), points: z.number().int().nonnegative(), requests: z.number().int().nonnegative() })), purposes: z.array(z.object({ id: z.string(), name: z.string(), points: z.number().int().nonnegative(), percent: z.number().min(0).max(100) })) })
export const employeeModelsResponseSchema = z.object({ meta: metaSchema, scope: scopeSchema, items: z.array(z.object({ id: z.string(), alias: z.string(), name: z.string(), purpose: z.string(), description: z.string(), capabilityTags: z.array(z.string()), contextLabel: z.string(), status: z.enum(['available', 'limited']), useAdvice: z.string(), providerAvailable: z.literal(false), actualModelAvailable: z.literal(false), channelAvailable: z.literal(false) })) })

export type EmployeeProfile = z.infer<typeof employeeProfileResponseSchema>
export type EmployeeKeys = z.infer<typeof employeeKeysResponseSchema>
export type EmployeeUsage = z.infer<typeof employeeUsageResponseSchema>
export type EmployeeModels = z.infer<typeof employeeModelsResponseSchema>
export class EmployeeApiError extends Error { constructor(message: string, readonly requestId?: string) { super(message) } }
async function getResource<T>(url: string, schema: z.ZodType<T>, signal?: AbortSignal) { const response = await fetch(url, { headers: { accept: 'application/json' }, signal }); const requestId = response.headers.get('x-request-id') ?? undefined; if (!response.ok) throw new EmployeeApiError('员工自助数据暂时无法加载', requestId); const parsed = schema.safeParse(await response.json()); if (!parsed.success) throw new EmployeeApiError('员工自助数据格式不符合接口约定', requestId); return parsed.data }
export function fetchEmployeeProfile(signal?: AbortSignal) { return getResource('/api/me', employeeProfileResponseSchema, signal) }
export function fetchEmployeeKeys(signal?: AbortSignal) { return getResource('/api/me/keys', employeeKeysResponseSchema, signal) }
export function fetchEmployeeUsage(period: '7d' | '30d', signal?: AbortSignal) { return getResource(`/api/me/usage?period=${period}`, employeeUsageResponseSchema, signal) }
export function fetchEmployeeModels(signal?: AbortSignal) { return getResource('/api/me/models', employeeModelsResponseSchema, signal) }
