import { describe, expect, it } from 'vitest'
import { usageDetailResponseSchema, usageFiltersSchema, usageResponseSchema } from './usage-api'

const item = { requestId: 'req-test-1', occurredAt: '2026-09-15T10:00:00.000Z', person: { id: 'person-1', name: '人员', department: { id: 'dept-1', name: '部门' } }, key: { id: 'key-1', masked: 'sk-ops••••••1234' }, purpose: { id: 'copy', name: '文案', alias: 'ecommerce-copy' }, model: { id: 'model-1', displayName: '模型', actualModel: 'model-1' }, channel: { id: 'channel-1', name: '渠道', type: 'official_api' }, protocol: 'responses', streamed: true, tokens: { input: 10, output: 20, total: 30 }, points: 1, latency: { firstTokenMs: 100, totalMs: 500 }, cost: { type: 'official_actual', amountUsd: .01, label: '官方实际' }, status: 'succeeded', error: null, conversationContentAvailable: false }
const list = { meta: { source: 'database', simulated: true, generatedAt: '2026-09-15T10:00:00.000Z', period: '7d', notice: '模拟数据' }, summary: { requests: 1, tokens: 30, points: 1, successRate: 100, p95LatencyMs: 500, costs: { officialActualUsd: .01, platformEstimateUsd: 0, cpaEstimateUsd: 0 } }, options: { people: [], departments: [], purposes: [], keys: [], models: [], channels: [] }, items: [item], pagination: { page: 1, pageSize: 10, total: 1, totalPages: 1 } }

describe('usage API contracts', () => {
  it('validates filters and explicit cost types', () => { expect(usageFiltersSchema.safeParse({ period: '7d', search: '', person: 'all', department: 'all', purpose: 'all', key: 'all', model: 'all', channel: 'all', status: 'all', costType: 'cpa_estimate', page: 1, pageSize: 10 }).success).toBe(true); expect(usageFiltersSchema.safeParse({ period: '90d', search: '', person: 'all', department: 'all', purpose: 'all', key: 'all', model: 'all', channel: 'all', status: 'all', costType: 'mixed', page: 1, pageSize: 10 }).success).toBe(false) })
  it('rejects conversation content and validates metadata-only details', () => { expect(usageResponseSchema.safeParse(list).success).toBe(true); const detail = { meta: { source: 'database', simulated: true, generatedAt: '2026-09-15T10:00:00.000Z', notice: '模拟数据' }, item, route: { alias: 'ecommerce-copy', retryCount: 0, requestIdPropagated: true }, client: { name: 'Codex Desktop', mode: 'stream' }, content: { stored: false, reason: '未采集' } }; expect(usageDetailResponseSchema.safeParse(detail).success).toBe(true); expect(usageDetailResponseSchema.safeParse({ ...detail, content: { stored: true, reason: '正文' } }).success).toBe(false) })
})
